name: var_test

on:
   push:
    push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
env:
 name: ADHI
 age: 23
jobs:
  build:
        runs-on: ubuntu-latest
        env:
        address: KERALA
    steps:
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: ls -la
